### ISSUE TITLE
Remove "About" view

### ISSUE THREAD

**Issue by swotge** [crunchersaspire/worshipsongs-android#252]

**Comment by GermanGospel** [comment]
@swotge - Why do you removed the README.md text from the app? I found it really interesting to read the background of the project in the app itself.

**Comment by swotge** [comment]
@GermanGospel, Enough details(About app) is available in [Play store description](https://play.google.com/store/apps/details?id=org.worshipsongs) and github [README.md](https://github.com/crunchersaspire/worshipsongs-android). So we feel **About** view is redundant, that is why we removed.

**Comment by GermanGospel** [comment]
@swotge - I don't think that a redundant advertisement is unusual, but then norm! ;-) I will install the app to all of smartphones of my church friends. I'm sure they would read the About view if it was there. But they will not read the Github project README.md and will only (maybe) read the PlayStore description if there is an update available...

As it is today, not even the PlayStore description and Github README.md are redundant, since the PlayStore description is outdated. I opened an issue for that: #309
https://play.google.com/store/apps/details?id=org.worshipsongs

**Comment by emailradhesh** [comment]
Normally, **About** is useful when there is no internet on the device. And may be give credit to concerned people.

**Comment by GermanGospel** [comment]
@emailradhesh - Maybe there is no internet connection! ;-) In the app itself there is no link to the "About" info (Github README.md or outdated PlayStore description) in the internet. The user has to hit "share" and manually copy the link to the web browser app...

**Comment by emailradhesh** [comment]
I second it @GermanGospel

**Comment by GermanGospel** [comment]
@swotge - The "About" view containted the FAQ. Which is missing now.

FAQ
Q. I couldn't find a song that I am looking for. What should I do?
...

**Comment by swotge** [comment]
@GermanGospel Next version will provide **About** view
